/// Builds a deterministic `/v1/transit/compute` response for the Gochar page and
/// controller tests. Values are shape-correct (not ephemeris-accurate): a natal
/// Moon in Pisces, Saturn running the peak leg of Sade Sati, a retrograde
/// Mercury and an exalted Jupiter, so the UI's full vocabulary is exercised.
Map<String, dynamic> sampleTransitResponseJson(String dateIso) {
  return <String, dynamic>{
    'profile': <String, dynamic>{'ayanamsha': 'lahiri_chitrapaksha'},
    'as_of': <String, dynamic>{
      'date': dateIso,
      'local_iso': '${dateIso}T12:00+05:30',
      'timezone': 'Asia/Kolkata',
      'is_today': true,
    },
    'observation_place': <String, dynamic>{
      'place_label': 'Mumbai',
      'latitude': 19.07,
      'longitude': 72.87,
      'timezone': 'Asia/Kolkata',
    },
    'natal': <String, dynamic>{
      'moon_rashi_index': 11,
      'moon_rashi': _name('Pisces', 'Meena'),
      'moon_nakshatra': 'Revati',
      'moon_pada': 2,
      'lagna_rashi_index': 6,
      'lagna_rashi': _name('Libra', 'Tula'),
      'sun_rashi_index': 1,
      'sun_rashi': _name('Taurus', 'Vrishabha'),
    },
    'planets': <Map<String, dynamic>>[
      _planet(
        key: 'sun',
        en: 'Sun',
        ve: 'Surya',
        rashiIndex: 1,
        rashiEn: 'Taurus',
        rashiVe: 'Vrishabha',
        nakshatra: 'Rohini',
        houseMoon: 3,
        houseLagna: 8,
        favourable: true,
        bindus: 4,
        sarva: 30,
      ),
      _planet(
        key: 'moon',
        en: 'Moon',
        ve: 'Chandra',
        rashiIndex: 3,
        rashiEn: 'Cancer',
        rashiVe: 'Karka',
        nakshatra: 'Pushya',
        houseMoon: 5,
        houseLagna: 10,
        favourable: false,
        bindus: 5,
        sarva: 28,
      ),
      _planet(
        key: 'mangal',
        en: 'Mars',
        ve: 'Mangal',
        rashiIndex: 0,
        rashiEn: 'Aries',
        rashiVe: 'Mesha',
        nakshatra: 'Bharani',
        houseMoon: 2,
        houseLagna: 7,
        favourable: false,
        dignity: 'own',
        bindus: 3,
        sarva: 24,
      ),
      _planet(
        key: 'budha',
        en: 'Mercury',
        ve: 'Budha',
        rashiIndex: 2,
        rashiEn: 'Gemini',
        rashiVe: 'Mithuna',
        nakshatra: 'Ardra',
        houseMoon: 4,
        houseLagna: 9,
        favourable: true,
        motion: 'retrograde',
        bindus: 6,
        sarva: 27,
      ),
      _planet(
        key: 'guru',
        en: 'Jupiter',
        ve: 'Guru',
        rashiIndex: 3,
        rashiEn: 'Cancer',
        rashiVe: 'Karka',
        nakshatra: 'Punarvasu',
        houseMoon: 5,
        houseLagna: 10,
        favourable: true,
        dignity: 'exalted',
        bindus: 5,
        sarva: 28,
      ),
      _planet(
        key: 'shukra',
        en: 'Venus',
        ve: 'Shukra',
        rashiIndex: 1,
        rashiEn: 'Taurus',
        rashiVe: 'Vrishabha',
        nakshatra: 'Krittika',
        houseMoon: 3,
        houseLagna: 8,
        favourable: true,
        dignity: 'own',
        bindus: 4,
        sarva: 30,
      ),
      _planet(
        key: 'shani',
        en: 'Saturn',
        ve: 'Shani',
        rashiIndex: 11,
        rashiEn: 'Pisces',
        rashiVe: 'Meena',
        nakshatra: 'Revati',
        houseMoon: 1,
        houseLagna: 6,
        favourable: false,
        bindus: 3,
        sarva: 23,
      ),
      _planet(
        key: 'rahu',
        en: 'Rahu',
        ve: 'Rahu',
        rashiIndex: 10,
        rashiEn: 'Aquarius',
        rashiVe: 'Kumbha',
        nakshatra: 'Shatabhisha',
        houseMoon: 12,
        houseLagna: 5,
        favourable: false,
        motion: 'retrograde',
        node: true,
        sarva: 21,
      ),
      _planet(
        key: 'ketu',
        en: 'Ketu',
        ve: 'Ketu',
        rashiIndex: 4,
        rashiEn: 'Leo',
        rashiVe: 'Simha',
        nakshatra: 'Magha',
        houseMoon: 6,
        houseLagna: 11,
        favourable: true,
        motion: 'retrograde',
        node: true,
        sarva: 29,
      ),
    ],
    'saturn': <String, dynamic>{
      'house_from_moon': 1,
      'rashi_index': 11,
      'rashi': _name('Pisces', 'Meena'),
      'status': 'sade_sati',
      'phase': 'peak',
      'window_start_iso': '2023-01-17T00:00+05:30',
      'window_start_date': '2023-01-17',
      'window_end_iso': '2030-04-17T00:00+05:30',
      'window_end_date': '2030-04-17',
      'progress_percent': 47.0,
      'legs': <Map<String, dynamic>>[
        <String, dynamic>{
          'phase': 'rising',
          'house_from_moon': 12,
          'rashi_index': 10,
          'rashi': _name('Aquarius', 'Kumbha'),
          'start_iso': '2023-01-17T00:00+05:30',
          'start_date': '2023-01-17',
          'end_iso': '2025-03-29T00:00+05:30',
          'end_date': '2025-03-29',
        },
        <String, dynamic>{
          'phase': 'peak',
          'house_from_moon': 1,
          'rashi_index': 11,
          'rashi': _name('Pisces', 'Meena'),
          'start_iso': '2025-03-29T00:00+05:30',
          'start_date': '2025-03-29',
          'end_iso': '2027-06-03T00:00+05:30',
          'end_date': '2027-06-03',
        },
        <String, dynamic>{
          'phase': 'setting',
          'house_from_moon': 2,
          'rashi_index': 0,
          'rashi': _name('Aries', 'Mesha'),
          'start_iso': '2027-06-03T00:00+05:30',
          'start_date': '2027-06-03',
          'end_iso': '2030-04-17T00:00+05:30',
          'end_date': '2030-04-17',
        },
      ],
      'next_start_iso': null,
      'next_start_date': null,
    },
    'double_transit': <String, dynamic>{
      'jupiter_sign_index': 3,
      'saturn_sign_index': 11,
      'double_transit_sign_indices': <int>[11],
      'active': true,
      'maha_dasha_lord': 'guru',
      'antar_dasha_lord': 'moon',
      'headline_houses': <int>[12],
      'event_window_houses': <int>[12],
      'signs': <Map<String, dynamic>>[
        <String, dynamic>{
          'sign_index': 11,
          'rashi': _name('Pisces', 'Meena'),
          'jupiter_relation': 'aspect_9',
          'saturn_relation': 'occupies',
          'house_from_moon': 1,
          'house_from_lagna': 6,
        },
      ],
      'bhavas': List<Map<String, dynamic>>.generate(12, (int i) {
        final house = i + 1;
        // House 12 from Lagna (Pisces) is the dasha-confirmed event window here.
        final isWindow = house == 12;
        return <String, dynamic>{
          'house': house,
          'sign_index': (5 + i) % 12,
          'rashi': _name('Sign$house', 'Sign$house'),
          'from_lagna': isWindow,
          'from_moon': isWindow,
          'karaka_key': house == 7 ? 'shukra' : 'guru',
          'karaka_under_double_transit': false,
          'dasha_linked': isWindow,
          'lord_key': 'guru',
          'lord_under_double_transit': isWindow,
          'is_double_transit': isWindow,
          'is_event_window': isWindow,
          'tier': isWindow ? 'event' : 'quiet',
          'strength_score': isWindow ? 6 : 0,
          'significations': <String>['area one', 'area two'],
        };
      }),
    },
    'ashtakavarga': <String, dynamic>{
      'sarva': <int>[31, 26, 27, 28, 29, 32, 31, 27, 34, 28, 21, 23],
      'bhinna': <String, dynamic>{
        'sun': <int>[4, 5, 4, 3, 6, 4, 5, 3, 4, 4, 3, 3],
        'moon': <int>[5, 4, 5, 5, 4, 3, 4, 5, 4, 4, 3, 3],
        'mangal': <int>[3, 4, 3, 2, 5, 3, 4, 3, 4, 3, 2, 3],
        'budha': <int>[5, 4, 6, 5, 4, 5, 4, 5, 4, 4, 4, 4],
        'guru': <int>[5, 4, 5, 5, 5, 4, 5, 4, 5, 5, 4, 5],
        'shukra': <int>[4, 4, 4, 4, 4, 5, 5, 5, 4, 4, 4, 5],
        'shani': <int>[5, 1, 0, 4, 1, 8, 4, 2, 9, 4, 1, 0],
      },
    },
    'highlights': <Map<String, dynamic>>[
      <String, dynamic>{
        'type': 'sade_sati',
        'planet_key': 'shani',
        'date': '2030-04-17',
        'rashi_index': 11,
      },
      <String, dynamic>{
        'type': 'retrograde',
        'planet_key': 'budha',
        'date': '2026-06-29',
        'rashi_index': 2,
      },
      <String, dynamic>{
        'type': 'exalted',
        'planet_key': 'guru',
        'date': null,
        'rashi_index': 3,
      },
    ],
  };
}

Map<String, dynamic> _name(String english, String vedic) =>
    <String, dynamic>{'english': english, 'vedic': vedic};

Map<String, dynamic> _planet({
  required String key,
  required String en,
  required String ve,
  required int rashiIndex,
  required String rashiEn,
  required String rashiVe,
  required String nakshatra,
  required int houseMoon,
  required int houseLagna,
  required bool favourable,
  String motion = 'direct',
  String dignity = 'none',
  bool node = false,
  int? bindus,
  required int sarva,
}) {
  return <String, dynamic>{
    'key': key,
    'name': _name(en, ve),
    'rashi_index': rashiIndex,
    'rashi': _name(rashiEn, rashiVe),
    'degree_in_sign': 12.5,
    'nakshatra': nakshatra,
    'pada': 2,
    'motion': motion,
    'retrograde': motion == 'retrograde',
    'combust': false,
    'dignity': dignity,
    'house_from_moon': houseMoon,
    'house_from_lagna': houseLagna,
    'phala_from_moon': <String, dynamic>{
      'favourable': favourable,
      'has_vedha_rule': !node,
      'vedha_obstructed': false,
      'vedha_house_from_moon': null,
      'vedha_by': null,
    },
    'ingress': <String, dynamic>{
      'entered_iso': '2026-05-01T00:00+05:30',
      'entered_date': '2026-05-01',
      'leaves_iso': '2026-08-01T00:00+05:30',
      'leaves_date': '2026-08-01',
    },
    'station': <String, dynamic>{
      'motion': motion,
      'next_station_iso': motion == 'retrograde' ? '2026-07-01T00:00+05:30' : null,
      'next_station_date': motion == 'retrograde' ? '2026-07-01' : null,
      'since_iso': null,
      'since_date': null,
    },
    'ashtakavarga': <String, dynamic>{
      'bindus': node ? null : bindus,
      'max_bindus': 8,
      'sarva_bindus': sarva,
    },
  };
}
